### ISSUE TITLE
Problem with Xamarin nuget reference

### ISSUE THREAD

**Issue by JensNordenbro** [adamped/xamarin-forms-pwa#1]
I cannot run this example from Visual Studio. The Nuget-reference for Xamarin.Forms has a warning sign. 

Is there a requirement for Installing SDK/Tooling for Xamarin. I do not have this now.

**Comment by adamped** [comment]
Rebuilding the project will download any appropriate nuget packages. I don't think you need to install the Xamarin tooling from the Visual Studio installer the project should at least build without it.
